version: "3.9"

services:
  slavarr:
    image: ghcr.io/sbondco/slavarr:latest
    container_name: slavarr
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
