version: "3.9"

# To test prod
services:
  slavarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slavarr
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
